package vendingmachine.utils

enum class ErrorType(val errorMessage: String) {
    POSITIVE(ERROR.format(ERROR_POSITIVE_NUMBER)),
    PRODUCT_PRICE(ERROR.format(ERROR_PRODUCT_PRICE)),
    PRODUCT_PRICE_RANGE(ERROR.format(ERROR_PRODUCT_PRICE_RANGE)),
    PRODUCT_DIVIDED_PRICE(ERROR.format(ERROR_PRODUCT_DIVIDED_PRICE)),
    PRODUCT_QUANTITY(ERROR.format(ERROR_PRODUCT_QUANTITY)),
    PRODUCT_NAME_LENGTH(ERROR.format(ERROR_PRODUCT_NAME_LENGTH)),
    PRODUCT_CONTAIN(ERROR.format(ERROR_PRODUCT_CONTAIN)),
    AMOUNT(ERROR.format(ERROR_AMOUNT))
}