package vendingmachine.utils

enum class ErrorType(val errorMessage: String) {
    RETENTION(ERROR.format(ERROR_RETENTION)),
    PRODUCT_PRICE(ERROR.format(ERROR_PRODUCT_PRICE)),
    PRODUCT_PRICE_RANGE(ERROR.format(ERROR_PRODUCT_PRICE_RANGE)),
    PRODUCT_DIVIDED_PRICE(ERROR.format(ERROR_PRODUCT_DIVIDED_PRICE)),
    PRODUCT_QUANTITY(ERROR.format(ERROR_PRODUCT_QUANTITY)),
    INPUT_AMOUNT(ERROR.format(ERROR_INPUT_AMOUNT))
}