package baseball.util

enum class ErrorType(val errorMessage: String) {
    BASEBALL_NUMBER_RANGE(ERROR.format(BASEBALL_NUMBER + ERRORL_BASEBALL_NUMBER_RANGE)),
    BASEBALL_NUMBER_SIZE(ERROR.format(BASEBALL_NUMBER + ERROR_BASEBALL_NUMBER_SIZE))
}