package bridge.uilts

enum class ErrorType(val errorMessage: String) {
    POSITIVE_NUMBER(ERROR.format(BRIDGE_SIZE + ERROR_POSITIVE_NUMBER)),
    NUMBER_RANGE(ERROR.format(BRIDGE_SIZE + ERROR_NUMBER_RANGE)),
    NOT_NUMBER(ERROR.format(BRIDGE_SIZE + ERROR_NOT_NUMBER)),
    DIRECTION(ERROR.format(MOVEMENT + ERROR_DIRECTION_COMMAND)),
    RETRY_COMMAND(ERROR.format(COMMAND + ERROR_RETRY_COMMAND)),
    EMPTY(ERROR.format(ERROR_EMPTY)),
    UPPER(ERROR.format(ERROR_UPPERCASE))
}